// <auto-generated />
using System;
using MahjongScore.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MahjongScore.Server.Persistence.Migrations
{
    [DbContext(typeof(MahjongDbContext))]
    [Migration("20260216140228_fix001")]
    partial class fix001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MahjongScore.Server.Persistence.MatchRecordEntity", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("FinalStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("final_state_json");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("logs_json");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("participants_json");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("MatchId");

                    b.ToTable("match_records", (string)null);
                });

            modelBuilder.Entity("MahjongScore.Server.Persistence.RoomEntity", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("history_json");

                    b.Property<string>("JoinKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("join_key");

                    b.Property<string>("LogsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("logs_json");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.HasKey("RoomId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("MahjongScore.Server.Persistence.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("IconDataUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_data_url");

                    b.Property<int>("RiichiVoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("riichi_voice_id");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
